### ISSUE TITLE
python 3.4 support broken by test part

### ISSUE THREAD

**Issue by f0ma** [Tyulis/rawutil#2]
In the test part of rawutil module (`if __name__ == '__main__':`) one line breaks python <= 3.4 compatibility:

```
Traceback (most recent call last):
  File "ubloxlogger.py", line 6, in <module>
    import ubloxfifo
  File "/root/ubloxlogger/ubloxfifo.py", line 2, in <module>
    import ubloxproto
  File "/root/ubloxlogger/ubloxproto.py", line 1, in <module>
    import rawutil, struct
  File "/usr/lib/python3.4/site-packages/rawutil.py", line 668
    pack(s, *data, file)
                   ^
SyntaxError: only named arguments may follow *expression
```
```
Python 3.4.3 (default, Aug  9 2016, 15:36:25) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
```
Changing this line to `pack(s, *(data+[file]))` fix this error.

**Comment by Tyulis** [comment]
Fixed it. Thanks !
